before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Mp6ADpkZsWomX7uyRJqxN8S43E3Ym9HoXSNKh/wpnGfO5McEmPpyDSqz2zMWMgsinNFuxyoNv7Ey3rJxrSYi6r5EOs8+lGdMupf85P9Sdz+u7dcNp139K3CX7pi5kIcQQqSYk94y+JPSoiR/pf/KnUYFqw24oG+o8GeGFKUA/1EdhnW6hE/OaoZA6FD54RhxjQTRGXMmFfbMLuU5Di4pUcxqerst0/vb/ZoepD79JQJyI09nxG8kA8SblMzD4O4FVqWnzbn3smrguk65HN4gmxXLf4v0jILjK8yK3gq8t7idDbAQ0xUy3sUyZ4tn1K6v1jvU2E47ShsxZCsScUXC7kKebl/sVvXwRDzjtFiGVQKydoa60FJG5ZoQWLWsfk55ZYPwtwG4B9g/Qv9etuQNEDzuswtK2tVPPF9tHZXxGCS6xp3DjvGiMRooPnOeDFBqKtG+NHL6Ss/aTCjAhJGNqR81ecZVfAXphOZ0Bc6S5XuMBadBfZHsFElc9xMb4iK3ghg3qlI+NZxu8ptxm+XKYe12fTcNcqPT+gvMwurMncbePVVYXo5vykz8ng7JBzLDS+hVLmnoqbOS6NLH2u5rDAC4Ozn/5/iS/iaHTlxzNhB8AaOvnxRPwWfpD0xW+odB5uTFxXcaxzZb53TifeiBzveaREHzCAHTFO0tAvDFUVc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
